# Generated by Django 3.1.6 on 2021-03-14 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210313_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
