# Generated by Django 3.1.6 on 2021-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_task_remind_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
