# Generated by Django 3.1.6 on 2021-03-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_task_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
