# Generated by Django 3.1.6 on 2021-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20210315_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
